# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

interpolate <- function(xData, yData, x) {
    .Call('_microsamplingDesign_interpolate', PACKAGE = 'microsamplingDesign', xData, yData, x)
}

interpolateVec <- function(xData, yData, x) {
    .Call('_microsamplingDesign_interpolateVec', PACKAGE = 'microsamplingDesign', xData, yData, x)
}

getFixedSchemePerformanceCpp <- function(popAvCurves, times) {
    .Call('_microsamplingDesign_getFixedSchemePerformanceCpp', PACKAGE = 'microsamplingDesign', popAvCurves, times)
}

